version: '3.2'
services:
  db:
    build:
      context: ../..
      dockerfile: ./cloud-build/integration-test/db/Dockerfile
      args: 
        - INFRABOX_BUILD_NUMBER=$INFRABOX_BUILD_NUMBER
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres

  app:
    build:
      context: ../..
      dockerfile: ./cloud-build/integration-test/app/Dockerfile
      args: 
        - VAR=test
    environment:
      - ENV_VARIABLE=test
    links:
      - db